---
- name: Creating a file
  hosts: all
  tasks:
  - name: Create a new group
    win_group:
      name: GGFamily
      description: Contain GG family members
      state: present

  - name: Create a user and add into group
    win_user:
      name: haifazahirah
      state: present
      groups:
        - GGFamily

  - name: Create a profile for an account at C:\Users\haifazahirah
    win_user_profile:
      username: haifazahirah
      state: present